This process tested on: CentOS Linux 7.3

To install as a systemd service:

  Deploy application to: /opt/slack-demo-ttt

  npm install

  npm install -g forever service-systemd

  # adduser ttt -s /sbin/nologin
  # mkdir /var/log/tttd
  # chown ttt:ttt /var/log/tttd
  # chmod 755 /var/log/tttd

On CentOS 7/systemd, you may try to use the included service template:
  # node-systemd add scripts/service-template.json
  # systemctl enable tttd
  # systemctl start tttd

